### ISSUE TITLE
Encoding UTF-8

### ISSUE THREAD

**Issue by EricWermelinger** [moreach/teachu-api#20]
Currently, we have some Problems with the encoding E.g.
- PrÃ¼fung (in Grades)
- SchÃ¶nenwerd (in Settings)

**Comment by OliUmbi** [comment]
This is probably a frontend problem 
Try setting request header to `Content-Type: application/json;charset=UTF-8`

**Comment by OliUmbi** [comment]
is this still relevant?

**Comment by M1chaCH** [comment]
> is this still relevant?
The problem still exists in the client, but i don't know any further info.

**Comment by EricWermelinger** [comment]
I will hopefully fix during next week :-)

**Comment by EricWermelinger** [comment]
Fixed
