### ISSUE TITLE
what endpoint should the grades screen use?

### ISSUE THREAD

**Issue by M1chaCH** [moreach/teachu-api#21]
Previously the removed endpoint [here](https://github.com/moreach/teachu-api/pull/6/commits/04ad9676e2f3173c284e17c0057ce4f4030b29b7#r895235956) was used.  
  
The current way would be for the student to use the `GET /exam`. Then I would request to add a URL parameter for the student id. This would help the implementation of the parent screen.

**Comment by reu24** [comment]
PR: https://github.com/moreach/teachu-api/pull/24
The endpoint will probably be `GET /grade/{studentId}`

**Comment by OliUmbi** [comment]
It's a bigger problem, especially with parents having multiple children

**Comment by OliUmbi** [comment]
Grade is implemented and documented in swagger or just ask
