### ISSUE TITLE
Child endpoint brocken

### ISSUE THREAD

**Issue by M1chaCH** [moreach/teachu-api#22]
Currently the child/{studentId} endpoint throws an exception.
[errorlog.txt](https://github.com/moreach/teachu-api/files/9034504/errorlog.txt) (called 2x)  
It was used for the parent to access the student grade data.  
In the future I would request to also use the `GET /exam` endpoint as a parent but with a `studentId` as URL parameter.   
(refers to #21)

**Comment by reu24** [comment]
Fixed
