### ISSUE TITLE
Class List one and only get request

### ISSUE THREAD

**Issue by EricWermelinger** [moreach/teachu-api#25]
### **Spezifikation**
1 Liste pro Klass wo de Schüeler dinne isch.
Mit Überschrift: Klasse BM19c (Sylvie Bonaparte)
Mit Felder: ProfileImage, Firstname, Lastname, Phone
OnClick: ProfileImage, Firstname, Lastname, Birthday, Sex, PLZ, City, Street, Phone, Name Parent 1, Phone Parent 1, Phone Parent 2, Phone Parent 2

1 Liste mit Lehrer
Mit Überschrift Lehrer
Mit Felder: ProfileImage, Firstname, Lastname, Phone
OnClick: ProfileImage, Firstname, Lastname, Sex, PLZ, City, Street, Phone

Alles glade i eim get Request.

### **DTO**
export interface ClassListDTO {
    classes: ClassListClassDTO[];
    teachers: ClassListTeacherDTO[];
}

export interface ClassListClassDTO {
    className: string;
    teacherName: string;
    students: ClassListStudentDTO[];
}

export interface ClassListStudentDTO {
    profileImage: string;
    firstName: string;
    lastName: string;
    birthday: Date;
    sex: Sex;
    postalCode: string;
    city: string;
    street: string;
    phone: string;
    nameParent1: string;
    phoneParent1: string;
    nameParent2: string;
    phoneParent2: string;
}

export interface ClassListTeacherDTO {
    profileImage: string;
    firstName: string;
    lastName: string;
    sex: Sex;
    postalCode: string;
    city: string;
    street: string;
    phone: string;
}

**Comment by OliUmbi** [comment]
Bruchemer würkli d parent infos? (würdi mer s läbe liechter mache ohni)

**Comment by OliUmbi** [comment]
Ich han mal en mock endpunkt implementiert mit es paar ahpassige
- s ganze isch jetzte en liste mit klassene wo ihri eigene lehrer und schüeller hend
- klasselehrer werdet gad direkt glade demit die nüme matche muesch (chasch maybe en geile user component mache wo wemmer drüber hovert gad alli infos gseht und den under em klassenname inefätze)
- ich han parent infos usegnoh will gand kei lust han (chömer gern spöter hinzuefüege
- alles sind externaluserdtos

Bispil
[
  {
    "name": "MockName",
    "classTeacher": {
      "email": "mock@email.ch",
      "role": "student",
      "firstName": "mockFirstname",
      "lastName": "mockLastname",
      "birthday": 1657930807355,
      "sex": "other",
      "city": "mockCity"
    },
    "students": [
      {
        "email": "mock@email.ch",
        "role": "student",
        "firstName": "mockFirstname",
        "lastName": "mockLastname",
        "birthday": 1657930807351,
        "sex": "other",
        "city": "mockCity"
      },
      {
        "email": "mock@email.ch",
        "role": "student",
        "firstName": "mockFirstname",
        "lastName": "mockLastname",
        "birthday": 1657930807353,
        "sex": "other",
        "city": "mockCity"
      },
      {
        "email": "mock@email.ch",
        "role": "student",
        "firstName": "mockFirstname",
        "lastName": "mockLastname",
        "birthday": 1657930807353,
        "sex": "other",
        "city": "mockCity"
      }
    ],
    "teachers": [
      {
        "email": "mock@email.ch",
        "role": "student",
        "firstName": "mockFirstname",
        "lastName": "mockLastname",
        "birthday": 1657930807354,
        "sex": "other",
        "city": "mockCity"
      },
      {
        "email": "mock@email.ch",
        "role": "student",
        "firstName": "mockFirstname",
        "lastName": "mockLastname",
        "birthday": 1657930807354,
        "sex": "other",
        "city": "mockCity"
      },
      {
        "email": "mock@email.ch",
        "role": "student",
        "firstName": "mockFirstname",
        "lastName": "mockLastname",
        "birthday": 1657930807355,
        "sex": "other",
        "city": "mockCity"
      }
    ]
  }, 
  ...
]
