### ISSUE TITLE
School Infos one and only get request

### ISSUE THREAD

**Issue by EricWermelinger** [moreach/teachu-api#26]
### **Spezifikation**
Wie ufde Zeichnig, aber Icon für pinnti obe rechts & wichtig farblich hervorghobe:
Ziitigslayout mit 1, 2 oder 3 Spalte.
Pro Iitrag: Ersteller, Datum, 1 oder 0 Bild, Titel, Text, Wichtig, Pinned
Sortiert nach Pinned, denne nach Datum abstigend.

Alles glade i eim get Request.

### **DTO**
export interface SchoolInfosDTO {
    schoolInfos: SchoolInfoDTO[];
}

export interface SchoolInfoDTO {
    creatorName: string;
    date: Date;
    image?: string;
    title: string;
    text: string;
    important: boolean;
    pinned: boolean;
}

**Comment by OliUmbi** [comment]
mock is implemented
