### ISSUE TITLE
latest maven build fails 

### ISSUE THREAD

**Issue by M1chaCH** [moreach/teachu-api#27]
LogLevel and ClassSubjectInterval seem to be missing  

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/LogRecord.java:[7,33] cannot find symbol
  symbol:   class LogLevel
  location: package ch.teachu.teachuapi.enums
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/LogRecord.java:[24,104] cannot find symbol
  symbol: class LogLevel
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/LogRecord.java:[73,26] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.generated.tables.records.LogRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/LogRecord.java:[80,12] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.generated.tables.records.LogRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/LogRecord.java:[112,39] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.generated.tables.records.LogRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/LogRecord.java:[117,39] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.generated.tables.records.LogRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/LogRecord.java:[137,18] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.generated.tables.records.LogRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/LogRecord.java:[162,12] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.generated.tables.records.LogRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/LogRecord.java:[187,12] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.generated.tables.records.LogRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/LogRecord.java:[215,29] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.generated.tables.records.LogRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/LogRecord.java:[227,72] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.generated.tables.records.LogRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/LogRecord.java:[250,62] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.generated.tables.records.LogRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/Log.java:[7,33] cannot find symbol
  symbol:   class LogLevel
  location: package ch.teachu.teachuapi.enums
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/SchoolClassSubject.java:[7,33] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: package ch.teachu.teachuapi.enums
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/SchoolClassSubjectRecord.java:[7,33] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: package ch.teachu.teachuapi.enums
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/SchoolClassSubjectRecord.java:[24,166] cannot find symbol
  symbol: class ClassSubjectInterval
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/SchoolClassSubject.java:[92,55] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.generated.tables.SchoolClassSubject
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/SchoolClassSubject.java:[178,71] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.generated.tables.SchoolClassSubject
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/SchoolClassSubjectRecord.java:[129,29] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.generated.tables.records.SchoolClassSubjectRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/SchoolClassSubjectRecord.java:[136,12] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.generated.tables.records.SchoolClassSubjectRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/SchoolClassSubjectRecord.java:[168,71] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.generated.tables.records.SchoolClassSubjectRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/SchoolClassSubjectRecord.java:[173,71] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.generated.tables.records.SchoolClassSubjectRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/SchoolClassSubjectRecord.java:[213,18] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.generated.tables.records.SchoolClassSubjectRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/SchoolClassSubjectRecord.java:[258,12] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.generated.tables.records.SchoolClassSubjectRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/SchoolClassSubjectRecord.java:[303,12] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.generated.tables.records.SchoolClassSubjectRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/SchoolClassSubjectRecord.java:[355,44] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.generated.tables.records.SchoolClassSubjectRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/SchoolClassSubjectRecord.java:[367,147] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.generated.tables.records.SchoolClassSubjectRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/records/SchoolClassSubjectRecord.java:[394,151] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.generated.tables.records.SchoolClassSubjectRecord
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/Log.java:[72,40] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.generated.tables.Log
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/generated/java/ch/teachu/teachuapi/generated/tables/Log.java:[158,39] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.generated.tables.Log
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/errorhandling/ExceptionHandling.java:[4,33] cannot find symbol
  symbol:   class LogLevel
  location: package ch.teachu.teachuapi.enums
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/util/LogUtil.java:[3,33] cannot find symbol
  symbol:   class LogLevel
  location: package ch.teachu.teachuapi.enums
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/util/LogUtil.java:[14,61] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.util.LogUtil
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/util/LogUtil.java:[24,59] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.util.LogUtil
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/auth/jobs/TokenJob.java:[4,33] cannot find symbol
  symbol:   class LogLevel
  location: package ch.teachu.teachuapi.enums
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/sql/generation/ClassSubjectIntervalConverter.java:[3,33] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: package ch.teachu.teachuapi.enums
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/sql/generation/ClassSubjectIntervalConverter.java:[6,73] cannot find symbol
  symbol: class ClassSubjectInterval
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/sql/generation/ClassSubjectIntervalConverter.java:[9,12] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.sql.generation.ClassSubjectIntervalConverter
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/sql/generation/ClassSubjectIntervalConverter.java:[14,22] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.sql.generation.ClassSubjectIntervalConverter
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/sql/generation/ClassSubjectIntervalConverter.java:[24,18] cannot find symbol
  symbol:   class ClassSubjectInterval
  location: class ch.teachu.teachuapi.sql.generation.ClassSubjectIntervalConverter
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/sql/generation/LogLevelConverter.java:[3,33] cannot find symbol
  symbol:   class LogLevel
  location: package ch.teachu.teachuapi.enums
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/sql/generation/LogLevelConverter.java:[6,61] cannot find symbol
  symbol: class LogLevel
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/sql/generation/LogLevelConverter.java:[9,12] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.sql.generation.LogLevelConverter
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/sql/generation/LogLevelConverter.java:[14,22] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.sql.generation.LogLevelConverter
[ERROR] /C:/_dev/00_git/TeachU/teachu-api/src/main/java/ch/teachu/teachuapi/sql/generation/LogLevelConverter.java:[24,18] cannot find symbol
  symbol:   class LogLevel
  location: class ch.teachu.teachuapi.sql.generation.LogLevelConverter
[INFO] 45 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.457 s
[INFO] Finished at: 2022-07-13T17:46:43+02:00
[INFO] ------------------------------------------------------------------------

**Comment by OliUmbi** [comment]
resolved
