### ISSUE TITLE
houston we got a problem

### ISSUE THREAD

**Issue by OliUmbi** [moreach/teachu-api#28]
Parent view is much more complicated then expected. 
Options:

- extra endpoint for parents
- optional param with userId
- db knows which child is selected

**Comment by EricWermelinger** [comment]
Optional parameter studentId?: string in every relevant request.
When null -> take studentid from auth, when set, take studentId set and validate that user has access.
Why does db needs to know?

**Comment by OliUmbi** [comment]
Solved it with request param = /endpoint?studentId=******
