### ISSUE TITLE
List of Kids from a Parent

### ISSUE THREAD

**Issue by EricWermelinger** [moreach/teachu-api#32]
Not sure if it already exists...
As a parent, I need to choice which of my kids i am currently seeing.
So we need a get request for this.
No input needed, we can get userId through auth.
Output list of
studentId: string;
firstName: string;
lastName: string;

**Comment by OliUmbi** [comment]
Get /parent

**Comment by OliUmbi** [comment]
returns id with external user object

**Comment by OliUmbi** [comment]
maybe we should go through the api togheter
