### ISSUE TITLE
sometimes api throws nullpointer

### ISSUE THREAD

**Issue by M1chaCH** [moreach/teachu-api#37]
i am sorry but I could not figure out any more info about this. Here is the error:  
![image](https://user-images.githubusercontent.com/67689103/181254498-b92aa670-7ff6-445f-a07e-f8008de20f2b.png)

  
When this error occurs i have to clear the local storage and login again. Reloading the page does not help. 🤷

**Comment by M1chaCH** [comment]
I found one way to recreate it.
1. login to frontend
2. restart backend
3. reload page in frontend
4. error 500 - name not found

**Comment by OliUmbi** [comment]
Fix mit mim sql das ich ned prüefe öbs null chan si. Nullpointer hani expected. luegs mer ah

**Comment by OliUmbi** [comment]
Chöntisch mer no säge welle endpunkt es isch

**Comment by OliUmbi** [comment]
Hans glaub usgfunde aber noned tested
