### ISSUE TITLE
only gif supported

### ISSUE THREAD

**Issue by M1chaCH** [moreach/teachu-api#38]
I tried to implement the profile image upload functionality. When sending a png to the /user POST i get the following error. 

![image](https://user-images.githubusercontent.com/67689103/181464781-e49c11d6-3440-4a64-98d6-56c2c6e24973.png)

Could you please support some more image types?  Is "image/*" possible? 
And is there any handling of the file size? Should i implement something like a max file size in the frontend?

**Comment by OliUmbi** [comment]
Max filesize is 1MB

**Comment by OliUmbi** [comment]
I cannot recreate the bug. I have no problems in swagger or postman

**Comment by M1chaCH** [comment]
You are right, sorry for that.  
Did not realize that "form-data" does something different than a normal object in the post request body.
