### ISSUE TITLE
Security Issue User not found & Password wrong should be same error

### ISSUE THREAD

**Issue by EricWermelinger** [moreach/teachu-api#39]
AuthService.java Line 47
if (userDAO.getId() == null) {
            throw new NotFoundException("Email " + loginRequest.getEmail());
        }

        if (!passwordEncoder.matches(loginRequest.getPassword(), userDAO.getPassword())) {
            throw new InvalidException("Password for email " + loginRequest.getEmail());
        }

Change to:
if (userDAO.getId() == null || !passwordEncoder.matches(loginRequest.getPassword(), userDAO.getPassword()))
throw new InvalidException("Password or Email is incorrect");
// please exactly "Password or Email is incorrect" because this is already in use in Frontend :-)

**Comment by OliUmbi** [comment]
I have changed it, but please do not base the error handling on the message
