### ISSUE TITLE
Change format of Timetable Endpoint

### ISSUE THREAD

**Issue by EricWermelinger** [moreach/teachu-api#42]
Due to some Angular stuff, it is not possible to trigger the endpoint from the Frontend as intended.
Can we instead of having an object to put into the parameters to the parameters:
- Parameter From in Format: yyyy-MM-dd
- Parameter To in Format: yyyy-MM-dd

When one of the parameters is invalid or wrong formatted, Backend can throw error.

**Comment by OliUmbi** [comment]
Is done, the dates are now in the request params
