### ISSUE TITLE
Timetable - GET Lessons

### ISSUE THREAD

**Issue by EricWermelinger** [moreach/teachu-api#9]
Input {
from: Date,
to: Date
}

Output
array von {
    class: string;
    subject: string;
    lessonNumber: number;
    date: Date;
    room: string;
    teacher: string;
    lessonId: string;
}

**Comment by OliUmbi** [comment]
Jo mer müend mal wäge de events no zämehocke

**Comment by OliUmbi** [comment]
mock is implemented
